* Ideas for Satellite communication hardening


** Blockchain command & control

Multiple communication channels to a satellite
Validate each action on multiple satellites

** Multi-satellite authentication

Multi-satellite authentication: Validate each communication with confirmation from other satellites nearby (Starlink especially, GPS also possible). Similar to blockchain mining validation.


** Stronger encryption

Improve security of transmission with more secure communication protocol: Random number generator with a seed. Beginning/end of each communication generate new 

Pre-generated strings for communication. What is the memory size on a satellite? What is the bandwidth usage of command channel?

CCSDS - encryption standards (blue/red/green book)


** OTP

Time-based OTP generation. Already used?


** Proxy

It is possible to communicate with a satellite only through a dedicated proxy


** Port knocking

Open a port/ip address only after a port knocking sequence is received


** Authorization

Isolate various users when sharing satellite resources among multiple users: 


** Geolocation confirmation

Critical operations must be confirmed from multiple ground stations. Detected by time and GPS. Usable for orbiting satellites.


** Telemetry IDS

- NORAD Telemetry

Analyze NORAD open telemetry data and predict:
- maintenance
- targeting
- security notification


